import 'dart:math';

import 'level_book.dart';

/// Drives a single Resonance puzzle.
///
/// The board is a grid of cells. Each non-wall cell is either *lit* (synced)
/// or *dim*. Tapping a cell flips that cell plus its orthogonal non-wall
/// neighbours. The puzzle is solved when every non-wall cell is lit.
///
/// Boards are generated by starting from the fully-lit (solved) state and
/// applying a deterministic, seeded sequence of taps. That guarantees every
/// puzzle is solvable, and lets us compute a fair "par" (the minimum number
/// of distinct taps a perfect solver needs — cells tapped an even number of
/// times during scrambling cancel out).
class BoardEngine {
  final LevelSpec spec;

  late final int rows;
  late final int cols;

  /// Flat row-major state. `true` = lit.
  late List<bool> _lit;

  /// Flat row-major wall mask. Wall cells never change and are ignored.
  late List<bool> _wall;

  int _par = 0;
  int _moves = 0;

  BoardEngine(this.spec) {
    rows = spec.rows;
    cols = spec.cols;
    _generate();
  }

  int get moves => _moves;
  int get par => _par;
  int get cellCount => rows * cols;

  int indexOf(int r, int c) => r * cols + c;
  bool isWall(int r, int c) => _wall[indexOf(r, c)];
  bool isLit(int r, int c) => _lit[indexOf(r, c)];

  /// Active (tappable) cells remaining dim — useful for hints / progress.
  int get dimRemaining {
    var n = 0;
    for (var i = 0; i < _lit.length; i++) {
      if (!_wall[i] && !_lit[i]) n++;
    }
    return n;
  }

  bool get isSolved => dimRemaining == 0;

  /// Stars for the finished puzzle: 3 if at or under par, 2 if close, else 1.
  int get earnedStars {
    if (isSolved == false) return 0;
    if (_moves <= _par) return 3;
    if (_moves <= _par + (_par * 0.5).ceil() + 1) return 2;
    return 1;
  }

  void _buildWalls() {
    _wall = List<bool>.filled(rows * cols, false);
    for (final w in spec.walls) {
      if (w >= 0 && w < _wall.length) _wall[w] = true;
    }
  }

  void _generate() {
    _buildWalls();
    _lit = List<bool>.filled(rows * cols, true);
    _moves = 0;

    final rng = Random(spec.seed);
    final tappable = <int>[];
    for (var i = 0; i < _lit.length; i++) {
      if (!_wall[i]) tappable.add(i);
    }
    if (tappable.isEmpty) {
      _par = 0;
      return;
    }

    // Track tap parity per cell: an even number of taps on a cell is a no-op,
    // so the count of odd-parity cells is the optimal solution length.
    final parity = List<bool>.filled(rows * cols, false);
    var depth = spec.scramble;
    if (depth < 1) depth = 1;

    for (var i = 0; i < depth; i++) {
      final idx = tappable[rng.nextInt(tappable.length)];
      _applyToggle(idx ~/ cols, idx % cols);
      parity[idx] = !parity[idx];
    }

    _par = parity.where((p) => p).length;

    // Guard against an accidentally-solved start (all taps cancelled out).
    if (isSolved) {
      final idx = tappable[rng.nextInt(tappable.length)];
      _applyToggle(idx ~/ cols, idx % cols);
      _par = 1;
    }
  }

  void _applyToggle(int r, int c) {
    _flip(r, c);
    switch (spec.rule) {
      case ToggleRule.cross:
        _flip(r - 1, c);
        _flip(r + 1, c);
        _flip(r, c - 1);
        _flip(r, c + 1);
        break;
      case ToggleRule.diagonal:
        _flip(r - 1, c - 1);
        _flip(r - 1, c + 1);
        _flip(r + 1, c - 1);
        _flip(r + 1, c + 1);
        break;
      case ToggleRule.star:
        _flip(r - 1, c);
        _flip(r + 1, c);
        _flip(r, c - 1);
        _flip(r, c + 1);
        _flip(r - 1, c - 1);
        _flip(r - 1, c + 1);
        _flip(r + 1, c - 1);
        _flip(r + 1, c + 1);
        break;
    }
  }

  void _flip(int r, int c) {
    if (r < 0 || r >= rows || c < 0 || c >= cols) return;
    final i = indexOf(r, c);
    if (_wall[i]) return;
    _lit[i] = !_lit[i];
  }

  /// Player tap. Returns false if the cell can't be tapped (out of range/wall).
  bool tap(int r, int c) {
    if (r < 0 || r >= rows || c < 0 || c >= cols) return false;
    if (_wall[indexOf(r, c)]) return false;
    _applyToggle(r, c);
    _moves++;
    return true;
  }

  /// Reset to the exact same starting board (deterministic via seed).
  void reset() => _generate();
}
