name: drop_ball
description: "DropBall: Neon Edition — an elemental orb logic puzzle."
publish_to: 'none'
version: 1.0.3+22

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo_white.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/Logo_white.png"

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false

  assets:
    - assets/game_assets/
    - assets/Logo_white.png
    - assets/Logo_name.png
    - assets/Logo_gray.png
